### ISSUE TITLE
インストール時にsyntax error発生

### ISSUE THREAD

**Issue by kohei2095** [pettan0818/mecab_direct_connecter#18]
次のエラーが発生するので対処よろしくお願いします。

(anaconda3-4.3.1) nishikawa@umeda:~/nishikawa/Reputation-UX_SEO/programs/sasaki_proj$ sudo pip install git+https://github.com/pettan0818/mecab_direct_connecter.git
The directory '/home/nishikawa/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nishikawa/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/pettan0818/mecab_direct_connecter.git
  Cloning https://github.com/pettan0818/mecab_direct_connecter.git to /tmp/pip-req-build-4t0w0inb
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-req-build-4t0w0inb/mecab_direct_connecter/api.py", line 25, in <module>
        from morphing import MecabMother
    ImportError: No module named 'morphing'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4t0w0inb/setup.py", line 4, in <module>
        from mecab_direct_connecter import __version__
      File "/tmp/pip-req-build-4t0w0inb/mecab_direct_connecter/__init__.py", line 2, in <module>
        from .api import MorphUnit, jpn_morph, setup, setup_path
      File "/tmp/pip-req-build-4t0w0inb/mecab_direct_connecter/api.py", line 34, in <module>
        from .language import lang_parser
      File "/tmp/pip-req-build-4t0w0inb/mecab_direct_connecter/language.py", line 79
        target_pos: int = latest_eng_start_pos.pop(0)
                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-4t0w0inb/

**Comment by pettan0818** [comment]
Python3.7以上を使ってみてください

**Comment by pettan0818** [comment]
直ったらクローズをお願いしますね。

**Comment by kohei2095** [comment]
はい！

2018年11月7日(水) 1:56 pettan0818 <notifications@github.com>:
